### ISSUE TITLE
Implement functions `TaskSeq.skip`, `skipWhile`, `where`, `truncate`, `take`, `insertAt`, `updateAt`, `forall`, `concat` (seq)

### ISSUE THREAD

**Issue by abelbraaksma** [fsprojects/FSharp.Control.TaskSeq#208]
Please add the following from the wish list of the front page:
 
TODO list:

- [x] `skip`, `take` ([#209](209))
- [x] `truncate` and `drop` (as with `Seq.truncate`, these are the counterparts of `take` and `skip` that do not throw) (see [#209](209))
- [x] `skipWhile`, `skipWhileAsync`, `skipWhileInclusive`, `skipWhileInclusiveAsync` ([#219](219))
   - for future reference, this review discussion is worth keeping: https://github.com/fsprojects/FSharp.Control.TaskSeq/pull/219/files#r1434220613
   - improvements: [#235](235)
- [x] `where` and `whereAsync` (to mimic `Seq`, but this is just an alias for `filter`) ([#217](217))
- [x] (`takeWhile` etc, see [#122](122) / [#126](122), already implemented)
   - improvements: [#235](235)
- [x] `insertAt`, `removeAt` and `updateAt`, plus `insertManyAt`, `removeManyAt` ~and `updateManyAt`~ ([#236](236))
- [x] `forall` and `forallAsync` ([#240](240))
- [x] `max`, `maxBy`, `min`, `minBy`, plus `maxByAsync` and `minByAsync` ([#221](221))
- [x] `concat` overloads  (for concatenating a taskseq of sequences/lists etc) ([#237](237))

Full list of signatures:

```f#
val take: count: int -> source: TaskSeq<'T> -> TaskSeq<'T>
val skip: count: int -> source: TaskSeq<'T> -> TaskSeq<'T>
val drop: count: int -> source: TaskSeq<'T> -> TaskSeq<'T>
val truncate: count: int -> source: TaskSeq<'T> -> TaskSeq<'T>

val skipWhile: predicate: ('T -> bool) -> source: TaskSeq<'T> -> TaskSeq<'T>
val skipWhileAsync: predicate: ('T -> #Task<bool>) -> source: TaskSeq<'T> -> TaskSeq<'T>
val skipWhileInclusive: predicate: ('T -> bool) -> source: TaskSeq<'T> -> TaskSeq<'T>
val skipWhileInclusiveAsync: predicate: ('T -> #Task<bool>) -> source: TaskSeq<'T> -> TaskSeq<'T>

val where: predicate: ('T -> bool) -> source: TaskSeq<'T> -> TaskSeq<'T>
val whereAsync: predicate: ('T -> #Task<bool>) -> source: TaskSeq<'T> -> TaskSeq<'T>

// these four already implemented:
val takeWhile: predicate: ('T -> bool) -> source: TaskSeq<'T> -> TaskSeq<'T>
val takeWhileAsync: predicate: ('T -> #Task<bool>) -> source: TaskSeq<'T> -> TaskSeq<'T>
val takeWhileInclusive: predicate: ('T -> bool) -> source: TaskSeq<'T> -> TaskSeq<'T>
val takeWhileInclusiveAsync: predicate: ('T -> #Task<bool>) -> source: TaskSeq<'T> -> TaskSeq<'T>

val insertAt: position:int -> value:'T -> source: TaskSeq<'T> -> TaskSeq<'T>
val removeAt: position:int -> source: TaskSeq<'T> -> TaskSeq<'T>
val updateAt: position:int -> value:'T -> source: TaskSeq<'T> -> TaskSeq<'T>

val insertManyAt: position:int -> values:TaskSeq<'T> -> source: TaskSeq<'T> -> TaskSeq<'T>
val removeManyAt: position:int -> count:int -> source: TaskSeq<'T> -> TaskSeq<'T>

val forall: predicate: ('T -> bool) -> source: TaskSeq<'T> -> Task<bool>
val forallAsync: predicate: ('T -> #Task<bool>) -> source: TaskSeq<'T> -> Task<bool>

val max: source:TaskSeq<'T> -> Task<'T> (requires comparison)
val min: source:TaskSeq<'T> -> Task<'T> (requires comparison)
val maxBy: projection: ('T -> 'U) -> source:TaskSeq<'T> -> Task<'T> (requires comparison)
val minBy: projection: ('T -> 'U) -> source:TaskSeq<'T> -> Task<'T> (requires comparison)
val maxByAsync: projection: ('T -> #Task<'U>) -> source:TaskSeq<'T> -> Task<'T> (requires comparison)
val minByAsync: projection: ('T -> #Task<'U>) -> source:TaskSeq<'T> -> Task<'T> (requires comparison)

// overloads for existing concat (which takes nested task sequences)
val concat: sources: TaskSeq<'T seq> -> TaskSeq<'T>
val concat: sources: TaskSeq<'T list> -> TaskSeq<'T>
val concat: sources: TaskSeq<'T array> -> TaskSeq<'T>
val concat: sources: TaskSeq<ResizeArray<'T>> -> TaskSeq<'T>
```

**Comment by abelbraaksma** [comment]
Done and dusted, part of the just released v0.4.0.
